apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: hassanashrafahmed/node-app
          ports:
            - name: http-port
              containerPort: 3000